// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import ()

type File struct {
	FileID       int64
	Parent       int64
	Name         string
	FileType     int64
	Length       int64
	Link         string
	Permissions  int64
	OwnerID      int64
	GroupID      int64
	LastWriteAt  int64
	LastAccessAt int64
}

type Page struct {
	FileID        int64
	PageNum       int64
	PageSizePower int64
	Data          []byte
}

type SchemaVersion struct {
	One     int64
	Version int64
}
