// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
)

type File struct {
	FileID       []byte
	Parent       []byte
	Name         string
	FileType     int64
	Length       int64
	LastWriteAt  sql.NullInt64
	LastAccessAt sql.NullInt64
}

type Page struct {
	FileID        []byte
	PageNum       int64
	PageSizePower int64
	Data          []byte
	LastWriteAt   sql.NullInt64
	LastReadAt    sql.NullInt64
	LastAcceessAt sql.NullInt64
}
